# Generated by Django 4.2.2 on 2023-06-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.TextField(max_length=100)),
                ('cus_email', models.EmailField(max_length=254)),
                ('cus_mobile', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.TextField()),
                ('pro_qty', models.TextField(max_length=100)),
                ('cus', models.ManyToManyField(to='M_t_M.customer')),
            ],
        ),
    ]
