# Generated by Django 4.2.2 on 2023-06-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_t_M', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
